---
- name: Install Docker and set up WordPress
  hosts: all
  remote_user: ec2-user
  become: yes
  tasks:
    - name: Install required packages
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - docker
        - python3-pip
        - python3-setuptools
      tags:
        - install_packages

    - name: Start and enable Docker service
      systemd:
        name: docker
        enabled: yes
        state: started
      tags:
        - start_docker


      
  #  - name: Set up SSH key
  #run: |
  #  echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
  #  chmod 600 ~/.ssh/id_rsa
   # ssh-keyscan -H your-ec2-instance-ip-or-dns >> ~/.ssh/known_hosts
  #env:
   # SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
#
 #   - name: Deploy WordPress
  # hosts: all
  # become: yes
#   tasks:
 #   - name: Copy WordPress files
 #     ansible.builtin.copy:
 #       src: /path/to/wordpress/files
 #       dest: /var/www/html/
 #     become: yes
 #     remote_user: ec2-user
 #     # Specify the private key file
 #     ansible_ssh_private_key_file: ~/.ssh/id_rsa
 
   

       

    - name: Pull and run WordPress container
      docker_container:
        name: wordpress
        image: wordpress:latest
        ports:
          - "80:80"
        volumes:
          - /path/to/wordpress:/var/www/html
        env:
          WORDPRESS_DB_HOST: terraform-20230922160837877800000001.ccsof6gvipaz.us-east-1.rds.amazonaws.com
          WORDPRESS_DB_USER: user
          WORDPRESS_DB_PASSWORD: userroot
          WORDPRESS_DB_NAME: db
        restart_policy: always
      tags:
        - run_wordpress

    

        

